import re
with open('app/src/main/java/com/example/studio/ui/LayersPanel.kt', 'r') as f:
    text = f.read()

text = text.replace('package com.example.studio.uiimport', 'package com.example.studio.ui\nimport')
text = text.replace('launchimport', 'launch\nimport')
text = text.replace('animation.*import', 'animation.*\nimport')
text = text.replace('foundation.*import', 'foundation.*\nimport')
text = text.replace('gestures.detectDragGesturesimport', 'gestures.detectDragGestures\nimport')
text = text.replace('gestures.detectDragGesturesAfterLongPressimport', 'gestures.detectDragGesturesAfterLongPress\nimport')
text = text.replace('foundation.layout.*import', 'foundation.layout.*\nimport')
text = text.replace('lazy.LazyColumnimport', 'lazy.LazyColumn\nimport')
text = text.replace('lazy.itemsIndexedimport', 'lazy.itemsIndexed\nimport')
text = text.replace('shape.RoundedCornerShapeimport', 'shape.RoundedCornerShape\nimport')
text = text.replace('material.icons.Iconsimport', 'material.icons.Icons\nimport')
text = text.replace('icons.filled.*import', 'icons.filled.*\nimport')
text = text.replace('material3.*import', 'material3.*\nimport')
text = text.replace('runtime.*import', 'runtime.*\nimport')
text = text.replace('ui.Alignmentimport', 'ui.Alignment\nimport')
text = text.replace('ui.Modifierimport', 'ui.Modifier\nimport')
text = text.replace('ui.draw.clipimport', 'ui.draw.clip\nimport')
text = text.replace('ui.draw.scaleimport', 'ui.draw.scale\nimport')
text = text.replace('ui.graphics.Colorimport', 'ui.graphics.Color\nimport')
text = text.replace('ui.graphics.graphicsLayerimport', 'ui.graphics.graphicsLayer\nimport')
text = text.replace('ui.input.pointer.pointerInputimport', 'ui.input.pointer.pointerInput\nimport')
text = text.replace('ui.layout.ContentScaleimport', 'ui.layout.ContentScale\nimport')
text = text.replace('ui.text.font.FontWeightimport', 'ui.text.font.FontWeight\nimport')
text = text.replace('ui.text.style.TextOverflowimport', 'ui.text.style.TextOverflow\nimport')
text = text.replace('ui.unit.dpimport', 'ui.unit.dp\nimport')
text = text.replace('ui.unit.spimport', 'ui.unit.sp\nimport')
text = text.replace('ui.zIndeximport', 'ui.zIndex\nimport')
text = text.replace('com.example.studio.model.StudioLayerimport', 'com.example.studio.model.StudioLayer\nimport')
text = text.replace('com.example.studio.model.LayerTypeimport', 'com.example.studio.model.LayerType\nimport')
text = text.replace('ui.theme.*import', 'ui.theme.*\nimport')
text = text.replace('ui.theme.Typographyimport', 'ui.theme.Typography\nimport')
text = text.replace('kotlinx.coroutines.launch@Composable', 'kotlinx.coroutines.launch\n\n@Composable')
text = text.replace('ui.zIndex@Composable', 'ui.zIndex\n\n@Composable')
text = text.replace('ui.theme.*@Composable', 'ui.theme.*\n\n@Composable')
text = text.replace('ui.theme.Typography@Composable', 'ui.theme.Typography\n\n@Composable')
text = text.replace('com.example.studio.model.LayerType@Composable', 'com.example.studio.model.LayerType\n\n@Composable')

with open('app/src/main/java/com/example/studio/ui/LayersPanel.kt', 'w') as f:
    f.write(text)
