import re

with open('app/src/main/java/com/example/studio/ui/WorkspaceScreen.kt', 'r') as f:
    content = f.read()

# Replace drawGeometry calls for OuterBorder
content = re.sub(
    r'(if \(\(bordersShadowsItem\.parameters\["OuterBorder_Enabled"\]\?\.value \?: 0f\) > 0\.5f\) \{\s*val size = bordersShadowsItem\.parameters\["OuterBorder_Size"\]\?\.value \?: 0f\s*val opacity = bordersShadowsItem\.parameters\["OuterBorder_Opacity"\]\?\.value \?: 1f\s*val r = bordersShadowsItem\.parameters\["OuterBorder_Color_R"\]\?\.value \?: 1f\s*val g = bordersShadowsItem\.parameters\["OuterBorder_Color_G"\]\?\.value \?: 1f\s*val b = bordersShadowsItem\.parameters\["OuterBorder_Color_B"\]\?\.value \?: 1f\s*val col = androidx.compose.ui.graphics.Color\(r, g, b\)\s*if \(size > 0f\) \{\s*val gradShader = getEffectGradientShader\("OuterBorder", bordersShadowsItem, layer.width, layer.height\)\s*drawGeometry\(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke\(width = size \* 2f\), isOverlay = false, gradientShader = gradShader)',
    r'if ((bordersShadowsItem.parameters["OuterBorder_Enabled"]?.value ?: 0f) > 0.5f) {\n            val size = bordersShadowsItem.parameters["OuterBorder_Size"]?.value ?: 0f\n            val cRad = bordersShadowsItem.parameters["OuterBorder_CornerRadius"]?.value\n            val opacity = bordersShadowsItem.parameters["OuterBorder_Opacity"]?.value ?: 1f\n            val r = bordersShadowsItem.parameters["OuterBorder_Color_R"]?.value ?: 1f\n            val g = bordersShadowsItem.parameters["OuterBorder_Color_G"]?.value ?: 1f\n            val b = bordersShadowsItem.parameters["OuterBorder_Color_B"]?.value ?: 1f\n            val col = androidx.compose.ui.graphics.Color(r, g, b)\n            if (size > 0f) {\n                val gradShader = getEffectGradientShader("OuterBorder", bordersShadowsItem, layer.width, layer.height)\n                val finalCRad = if (cRad != null && cRad > 0f) cRad else null\n                drawGeometry(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke(width = size * 2f), isOverlay = false, gradientShader = gradShader, cornerRadiusOverride = finalCRad)',
    content
)

# Replace OuterStroke
content = re.sub(
    r'(if \(\(bordersShadowsItem\.parameters\["OuterStroke_Enabled"\]\?\.value \?: 0f\) > 0\.5f\) \{\s*val size = bordersShadowsItem\.parameters\["OuterStroke_Size"\]\?\.value \?: 0f\s*val opacity = bordersShadowsItem\.parameters\["OuterStroke_Opacity"\]\?\.value \?: 1f\s*val r = bordersShadowsItem\.parameters\["OuterStroke_Color_R"\]\?\.value \?: 1f\s*val g = bordersShadowsItem\.parameters\["OuterStroke_Color_G"\]\?\.value \?: 1f\s*val b = bordersShadowsItem\.parameters\["OuterStroke_Color_B"\]\?\.value \?: 1f\s*val col = androidx.compose.ui.graphics.Color\(r, g, b\)\s*if \(size > 0f\) \{\s*val gradShader = getEffectGradientShader\("OuterStroke", bordersShadowsItem, layer.width, layer.height\)\s*drawGeometry\(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke\(width = size \* 2f\), isOverlay = false, gradientShader = gradShader)',
    r'if ((bordersShadowsItem.parameters["OuterStroke_Enabled"]?.value ?: 0f) > 0.5f) {\n            val size = bordersShadowsItem.parameters["OuterStroke_Size"]?.value ?: 0f\n            val cRad = bordersShadowsItem.parameters["OuterStroke_CornerRadius"]?.value\n            val opacity = bordersShadowsItem.parameters["OuterStroke_Opacity"]?.value ?: 1f\n            val r = bordersShadowsItem.parameters["OuterStroke_Color_R"]?.value ?: 1f\n            val g = bordersShadowsItem.parameters["OuterStroke_Color_G"]?.value ?: 1f\n            val b = bordersShadowsItem.parameters["OuterStroke_Color_B"]?.value ?: 1f\n            val col = androidx.compose.ui.graphics.Color(r, g, b)\n            if (size > 0f) {\n                val gradShader = getEffectGradientShader("OuterStroke", bordersShadowsItem, layer.width, layer.height)\n                val finalCRad = if (cRad != null && cRad > 0f) cRad else null\n                drawGeometry(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke(width = size * 2f), isOverlay = false, gradientShader = gradShader, cornerRadiusOverride = finalCRad)',
    content
)

# InnerBorder
content = re.sub(
    r'(if \(\(bordersShadowsItem\.parameters\["InnerBorder_Enabled"\]\?\.value \?: 0f\) > 0\.5f\) \{\s*val size = bordersShadowsItem\.parameters\["InnerBorder_Size"\]\?\.value \?: 0f\s*val opacity = bordersShadowsItem\.parameters\["InnerBorder_Opacity"\]\?\.value \?: 1f\s*val r = bordersShadowsItem\.parameters\["InnerBorder_Color_R"\]\?\.value \?: 1f\s*val g = bordersShadowsItem\.parameters\["InnerBorder_Color_G"\]\?\.value \?: 1f\s*val b = bordersShadowsItem\.parameters\["InnerBorder_Color_B"\]\?\.value \?: 1f\s*val col = androidx.compose.ui.graphics.Color\(r, g, b\)\s*if \(size > 0f\) \{\s*val gradShader = getEffectGradientShader\("InnerBorder", bordersShadowsItem, layer.width, layer.height\)\s*val pathCachedObj = layerPath\s*if \(pathCachedObj\.asAndroidPath\(\)\.isEmpty\) \{\s*drawGeometry\(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke\(width = size\), gradientShader = gradShader\)\s*\} else \{\s*clipPath\(pathCachedObj\) \{\s*drawGeometry\(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke\(width = size \* 2f\), gradientShader = gradShader\)\s*\}\s*\})',
    r'if ((bordersShadowsItem.parameters["InnerBorder_Enabled"]?.value ?: 0f) > 0.5f) {\n            val size = bordersShadowsItem.parameters["InnerBorder_Size"]?.value ?: 0f\n            val cRad = bordersShadowsItem.parameters["InnerBorder_CornerRadius"]?.value\n            val opacity = bordersShadowsItem.parameters["InnerBorder_Opacity"]?.value ?: 1f\n            val r = bordersShadowsItem.parameters["InnerBorder_Color_R"]?.value ?: 1f\n            val g = bordersShadowsItem.parameters["InnerBorder_Color_G"]?.value ?: 1f\n            val b = bordersShadowsItem.parameters["InnerBorder_Color_B"]?.value ?: 1f\n            val col = androidx.compose.ui.graphics.Color(r, g, b)\n            if (size > 0f) {\n                val gradShader = getEffectGradientShader("InnerBorder", bordersShadowsItem, layer.width, layer.height)\n                val finalCRad = if (cRad != null && cRad > 0f) cRad else null\n                val pathCachedObj = layerPath\n                if (pathCachedObj.asAndroidPath().isEmpty) {\n                    drawGeometry(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke(width = size), gradientShader = gradShader, cornerRadiusOverride = finalCRad)\n                } else {\n                    clipPath(pathCachedObj) {\n                        drawGeometry(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke(width = size * 2f), gradientShader = gradShader, cornerRadiusOverride = finalCRad)\n                    }\n                }',
    content
)

# InnerStroke
content = re.sub(
    r'(if \(\(bordersShadowsItem\.parameters\["InnerStroke_Enabled"\]\?\.value \?: 0f\) > 0\.5f\) \{\s*val size = bordersShadowsItem\.parameters\["InnerStroke_Size"\]\?\.value \?: 0f\s*val opacity = bordersShadowsItem\.parameters\["InnerStroke_Opacity"\]\?\.value \?: 1f\s*val r = bordersShadowsItem\.parameters\["InnerStroke_Color_R"\]\?\.value \?: 1f\s*val g = bordersShadowsItem\.parameters\["InnerStroke_Color_G"\]\?\.value \?: 1f\s*val b = bordersShadowsItem\.parameters\["InnerStroke_Color_B"\]\?\.value \?: 1f\s*val col = androidx.compose.ui.graphics.Color\(r, g, b\)\s*if \(size > 0f\) \{\s*val gradShader = getEffectGradientShader\("InnerStroke", bordersShadowsItem, layer.width, layer.height\)\s*val pathCachedObj = layerPath\s*if \(pathCachedObj\.asAndroidPath\(\)\.isEmpty\) \{\s*drawGeometry\(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke\(width = size\), gradientShader = gradShader\)\s*\} else \{\s*clipPath\(pathCachedObj\) \{\s*drawGeometry\(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke\(width = size \* 2f\), gradientShader = gradShader\)\s*\}\s*\})',
    r'if ((bordersShadowsItem.parameters["InnerStroke_Enabled"]?.value ?: 0f) > 0.5f) {\n            val size = bordersShadowsItem.parameters["InnerStroke_Size"]?.value ?: 0f\n            val cRad = bordersShadowsItem.parameters["InnerStroke_CornerRadius"]?.value\n            val opacity = bordersShadowsItem.parameters["InnerStroke_Opacity"]?.value ?: 1f\n            val r = bordersShadowsItem.parameters["InnerStroke_Color_R"]?.value ?: 1f\n            val g = bordersShadowsItem.parameters["InnerStroke_Color_G"]?.value ?: 1f\n            val b = bordersShadowsItem.parameters["InnerStroke_Color_B"]?.value ?: 1f\n            val col = androidx.compose.ui.graphics.Color(r, g, b)\n            if (size > 0f) {\n                val gradShader = getEffectGradientShader("InnerStroke", bordersShadowsItem, layer.width, layer.height)\n                val finalCRad = if (cRad != null && cRad > 0f) cRad else null\n                val pathCachedObj = layerPath\n                if (pathCachedObj.asAndroidPath().isEmpty) {\n                    drawGeometry(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke(width = size), gradientShader = gradShader, cornerRadiusOverride = finalCRad)\n                } else {\n                    clipPath(pathCachedObj) {\n                        drawGeometry(col, opacity, androidx.compose.ui.graphics.drawscope.Stroke(width = size * 2f), gradientShader = gradShader, cornerRadiusOverride = finalCRad)\n                    }\n                }',
    content
)

with open('app/src/main/java/com/example/studio/ui/WorkspaceScreen.kt', 'w') as f:
    f.write(content)
